# Generated by Django 6.0.7 on 2026-07-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_demo_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('fleet_manager', 'Fleet Manager'), ('dispatcher', 'Dispatcher'), ('safety_officer', 'Safety Officer'), ('financial_analyst', 'Financial Analyst'), ('admin', 'Admin')], default='dispatcher', max_length=30),
        ),
    ]
