# Generated by Django 6.0.7 on 2026-07-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('license_plate', models.CharField(blank=True, default='', max_length=50)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('make', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=50)),
                ('max_load_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odometer', models.IntegerField(default=0)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('In Shop', 'In Shop'), ('Retired', 'Retired')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
