# Generated by Django 6.0.7 on 2026-07-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
