from django.urls import path
from .views import (
    TripHistoryReportView,
    VehicleUtilizationReportView,
    FuelCostReportView,
    ExpenseReportView,
    ExecutiveKPIsView,
    FleetAnalyticsView,
    TripAnalyticsView,
    DriverAnalyticsView,
    MaintenanceAnalyticsView,
    FuelAnalyticsView,
    ExpenseAnalyticsView,
    CustomReportView,
    ExportCSVView,
    ExportExcelView
)

urlpatterns = [
    path('trip-history/', TripHistoryReportView.as_view(), name='report_trip_history'),
    path('trip-history', TripHistoryReportView.as_view()),
    path('vehicle-utilization/', VehicleUtilizationReportView.as_view(), name='report_vehicle_utilization'),
    path('vehicle-utilization', VehicleUtilizationReportView.as_view()),
    path('fuel-cost/', FuelCostReportView.as_view(), name='report_fuel_cost'),
    path('fuel-cost', FuelCostReportView.as_view()),
    path('expense/', ExpenseReportView.as_view(), name='report_expense'),
    path('expense', ExpenseReportView.as_view()),

    path('fleet-summary/', FuelCostReportView.as_view(), name='report_fleet_summary'),
    path('fleet-summary', FuelCostReportView.as_view()),
    path('vehicle-performance/', VehicleUtilizationReportView.as_view(), name='report_vehicle_performance'),
    path('vehicle-performance', VehicleUtilizationReportView.as_view()),
    path('driver-performance/', TripHistoryReportView.as_view(), name='report_driver_performance'),
    path('driver-performance', TripHistoryReportView.as_view()),
    path('financial-summary/', ExpenseReportView.as_view(), name='report_financial_summary'),
    path('financial-summary', ExpenseReportView.as_view()),

    path('executive-kpis/', ExecutiveKPIsView.as_view(), name='report_executive_kpis'),
    path('executive-kpis', ExecutiveKPIsView.as_view()),
    path('fleet/', FleetAnalyticsView.as_view(), name='report_fleet_analytics'),
    path('fleet', FleetAnalyticsView.as_view()),
    path('trips/', TripAnalyticsView.as_view(), name='report_trip_analytics'),
    path('trips', TripAnalyticsView.as_view()),
    path('drivers/', DriverAnalyticsView.as_view(), name='report_driver_analytics'),
    path('drivers', DriverAnalyticsView.as_view()),
    path('maintenance/', MaintenanceAnalyticsView.as_view(), name='report_maintenance_analytics'),
    path('maintenance', MaintenanceAnalyticsView.as_view()),
    path('fuel/', FuelAnalyticsView.as_view(), name='report_fuel_analytics'),
    path('fuel', FuelAnalyticsView.as_view()),
    path('expenses/', ExpenseAnalyticsView.as_view(), name='report_expense_analytics'),
    path('expenses', ExpenseAnalyticsView.as_view()),
    path('custom/', CustomReportView.as_view(), name='report_custom'),
    path('custom', CustomReportView.as_view()),
    path('export/csv/', ExportCSVView.as_view(), name='report_export_csv'),
    path('export/csv', ExportCSVView.as_view()),
    path('export/excel/', ExportExcelView.as_view(), name='report_export_excel'),
    path('export/excel', ExportExcelView.as_view()),
]
